export const VEC_ICON_NAME = {
    RADIO_BUTTON_ICON: "RadioButtonIcon",
    SORT_ICON: "SortIcon",
    STEP_DONE_ICON: "StepDoneIcon",
    EXPORT_ICON: "ExportIcon",
    PLUS_ICON: "PlusIcon",
    FILE_UPLOADING_ICON: "FileUploadingIcon",
    UPLOAD_ICON: "UploadIcon",
    DASHBOARD_ICON: "DashboardIcon",
    ALLERGIES_ICON: "AllergiesIcon",
    DIAGNOSES_ICON: "DiagnosesIcon",
    MEDICATION_ICON: "MedicationsIcon",
    VITALS_ICON: "VitalsIcon",
    LAB_ICON: "LabIcon",
    IMAGING_ICON: "ImagingIcon",
    HISTORY_ICON: "HistoryIcon",
    DOCUMENTS_ICON: "DocumentsIcon",
    APPOINTMENTS_ICON: "AppointmentsIcon",
    BILLING_ICON: "BillingIcon",
    INSURANCE_ICON: "InsuranceIcon",
    CARD_DETAILS_ICON: "CardDetailsIcon",
    PROFILE_ICON: "ProfileIcon",
    PORTAL_ACCESS_ICON: "PortalAccessIcon",
    VACCINES_ICON: "VaccinesIcon",
    CALL_ICON: "CallIcon",
    LOCATION_ICON: "LocationIcon",
    FAX_ICON: "FaxIcon",
    EMAIL_ICON: "EmailIcon",
    PST_ICON: "PstIcon",
    CONTACT_ICON: "ContactIcon",
    CALENDAR_ICON: "CalendarIcon",
    TRANSLATE_ICON: "TranslateIcon",
    LOCATION_ICON_2: "LocationIcon2",
    ACTION_MENU_ICON: "ActionMenuIcon",
    BLACK_PLUS_ICON: "BlackPlusIcon",
    UPLOAD_CLOUD_IMAGE: "UploadCloudImage",
    CHECKBOX_DASH_ICON: "CheckboxDashIcon",
    CHECKBOX_ICON: "CheckBoxIcon",
    EDIT_ICON: "EditIcon",
    DELETE_ICON: "DeleteIcon",
    CALENDER_IMG: "CalenderImg",
    NEXT_ICON: "NextIcon",
    ACCOUNT_IMG: "AccountImg",
    CLOSE_ICON: "CloseIcon",
    VISA_ICON: "VisaIcon",
    LOCK_ICON: "LockIcon",
    ROUNDED_PLUS_ICON: "RoundedPlusIcon",
    THINK_EMR_LOGO_ICON: "ThinkEmrLogoIcon,",
    BACK_ICON: "BackIcon",
    IMAGE_ICON: "ImageIcon",
    PROVIDER_ICON: "ProviderIcon",
    TRENDING_UP: "TrendingUp",
    PATIENT_ICON: "PatientIcon",
    APPOINTMENT_ICON: "AppointmentIcon",
    ENCOUNTERS_ICON: "EncountersIcon",
    TRENDING_DOWN: "TrendingDown",
    FILTER_ICON: "FilterIcon",
    BLANK_TASK: "BlankTask",
    UP_ARROW: "UpArrow",
    DOWN_ARROW: "DownArrow",
    COLLAPSE_FITLER: "ColapseFilter",
    FILE_ICON: "FileIcon",
    MESSAGING_ICON: "MessagingIcon",
    URL_ICON: "UrlIcon",
    ADD_PERSON_ICON: "AddPersonIcon",
    VIDEO_BACKGROUND_PROFILE: "VideoBackgroundProfile",
    MICROPHONE_ICON: "MicroPhoneIcon",
    SPEAKER_ICON: "SpeakerIcon",
    VIDEO_CAM_ICON: "VideoCamIcon",
    SUCCESSFULLCHECK: "SuccessFullCheck",
    UNMUTE_MIC_ICON: "UnMuteMicIcon",
    MUTE_MIC_ICON: "MuteMicIcon",
    OFF_CAMERA: "OffCamera",
    ON_CAMERA: "OnCamera",
    SCREEN_SHARE_ICON: "ScreenShareIcon",
    CALL_RECORDING_ICON: "CallRecordingIcon",
    LEAVE_MEETING_ICON: "LeaveMeetingIcon",
    ADD_GUEST_ICON: "AddGuestIcon",
    ZOOM_CHAT_ICON: "ZoomChatIcon",
    ZOOM_SETTING_ICON: "ZoomSettingIcon",
    VOLUME_UP_ICON: "VolumeUpIcon",
    EXIT_FULL_SCREEN: "ExitFullScreen",
    VIDEO_CALL_ICON: "VideoCallIcon",
    SHARE_DOCUMENT_ICON: "ShareDocumentIcon",
    SEND_MESSAGE_ICON: "SendMessageIcon",
    SEND_EMOJI_ICON: "SendEmojiIcon",
    COPY_ICON: "CopyIcon",
    BLOOD_PRESSURE : "BloodPressure",
    RESPIRATION_RATE : "RespirationRate",
    HEART_RATE : "HeartRate",
    BODY_MASS_INDEX : "BodyMassIndex",
    VISIBILITY_ICON: "VisibilityIcon",
    OPEN_ENCOUNTER_ICON : "OpenEncounterIcon",
    PRINTER_ICON : "PrinterIcon",
    CHART_ICON : "ChartIcon",
    PHONE_ICON : "PhoneIcon",
    PERSON_ICON : "PersonIcon",
    CLOCK_ICON : "ClockIcon",
    ZOOM_MEET_ICON : "ZoomMeetIcon",
    DESCRIPTION_ICON : "DescriptionIcon",
    INFO_ICON : "InfoIcon",
    EDIT_DETAILS_ICON : "EditDetailsIcon",
    RIGHT_TICK_ICON : "RightTickIcon",
    WRONG_TICK_ICON : "WrongTickIcon",
    START_ENCOUNTER_ICON: "StartEncounterIcon",
    VIEW_EYE: "viewEye",
    TRIGGER_PATIENT_ICON: "TriggerPatientIcon",
    UPLOAD_ICON_SHORT: "UploadIconShort",
    DATEPICKER_CALENDARL_ICON : 'CalendarDatePickerIcon',
    EXPAND_ICON : 'ExpandIcon',
    EYE_VISIBILITY_ICON:'EyeVisibilityIcon',
    EYE_VISIBILITY_OFF_ICON:'EyeVisibilityOffIcon',
    ARROW_BACK_ICON : 'ArrowBackIcon',
    SEARCH_ICON : 'SearchIcon',
    PAYMENT_SUCCESS_ICON: 'PaymentSucessIcon'
};
